name: customer_new
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.15+5

environment:
  sdk: ^3.7.2

dependencies:
  address_core:
    path: module/core/address_core
  authentication_core:
    path: module/core/authentication_core
  banner_core:
    path: module/core/banner_core
  deposit_core:
    path: module/core/deposit_core
  notification_core:
    path: module/core/notification_core
  payment_core:
    path: module/core/payment_core
  product_core:
    path: module/core/product_core
  reseller_core:
    path: module/core/reseller_core
  sales_core:
    path: module/core/sales_core
  transaction_core:
    path: module/core/transaction_core
  user_core:
    path: module/core/user_core

  address_feature:
    path: module/features/address_feature
  authentication_feature:
    path: module/features/authentication_feature
  banner_feature:
    path: module/features/banner_feature
  bottom_navigator_feature:
    path: module/features/bottom_navigator_feature
  change_name_feature:
    path: module/features/change_name_feature
  change_number_feature:
    path: module/features/change_number_feature
  checkout_feature:
    path: module/features/checkout_feature
  dashboard_feature:
    path: module/features/dashboard_feature
  deposit_feature:
    path: module/features/deposit_feature
  failure_feature:
    path: module/features/failure_feature
  notification_feature:
    path: module/features/notification_feature
  onboarding_feature:
    path: module/features/onboarding_feature
  otp_feature:
    path: module/features/otp_feature
  payment_feature:
    path: module/features/payment_feature
  reseller_submission_feature:
    path: module/features/reseller_submission_feature
  review_feature:
    path: module/features/review_feature
  signin_feature:
    path: module/features/signin_feature
  signup_feature:
    path: module/features/signup_feature
  transaction_feature:
    path: module/features/transaction_feature
 
  flutter:
    sdk: flutter

  shared_arguments:
    path: module/shareds/shared_arguments
  shared_common:
    path: module/shareds/shared_common
  shared_libraries:
    path: module/shareds/shared_libraries

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/images/
    - assets/jsons/
