name: authentication_feature
description: "A new Flutter package project."
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  authentication_core:
    path: ../../core/authentication_core
  user_core:
    path: ../../core/user_core

  shared_common:
    path: ../../shareds/shared_common
  shared_libraries:
    path: ../../shareds/shared_libraries

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  very_good_analysis: ^7.0.0

flutter:
  generate: true
