name: shared_libraries
description: "A new Flutter package project."
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  equatable: ^2.0.7
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_countdown_timer: ^4.1.0
  flutter_feather_icons: ^2.0.0
  flutter_iconly: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_rating_stars: ^1.1.0
  flutter_slidable: ^3.1.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  flutter_swiper_view: ^1.1.8
  flutter_widget_from_html_core: ^0.16.0
  fluttertoast: ^8.2.12
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.3
  get_it: ^8.0.3
  google_fonts: 6.2.1
  google_maps_flutter: ^2.11.0
  http: ^1.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.19.0
  onesignal_flutter: ^5.3.0
  pinput: ^5.0.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  slide_countdown: ^2.0.2
  timeago: ^3.7.0
  timer_count_down: ^2.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter: null
