name: payment_core
description: "A new Flutter package project."
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared_common:
    path: ../../shareds/shared_common
  shared_libraries:
    path: ../../shareds/shared_libraries
  shared_utilities:
    path: ../../shareds/shared_utilities

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  very_good_analysis: ^6.0.0

flutter: null
